[WIP] Persistence
harmony-dev/beacon-chain-java pull request #162
Opened 2019-08-07 08:39 UTC by mkalinin

### What was done? (so far)
- A new database kind added; it featured with write buffer and designed to work with various storage engines like RocksDB
- Two flushing strategies is implemented:
  - instant: emits flushing on each commit
  - buffer size observer: emits flushing each time when buffer size exceeds predefined limit
- RocksDB source is implemented
- Basic tests for database, rocksdb source and their superposition

### Yet to do
- Javadocs
- Connect database driven by RocksDB to `node` binary

2019-08-07 08:51 UTC, Nashatyrev approved these changes
Looks nice

2019-08-07 09:33 UTC, zilm13 requested changes
LGTM
but tests are failed

2019-08-14 08:06 UTC, zilm13 approved these changes
LGTM

2019-08-14 08:06 UTC, zilm13 commented on start/common/src/main/java/org/ethereum/beacon/start/common/NodeLauncher.java
> +    db = Database.rocksDB(Paths.get(computeDbName(chainStartEvent)).toString(), 64L << 20);
what does this magic number means?

2019-08-14 09:59 UTC, mkalinin commented on start/common/src/main/java/org/ethereum/beacon/start/common/NodeLauncher.java
> +    db = Database.rocksDB(Paths.get(computeDbName(chainStartEvent)).toString(), 64L << 20);
Fixed!

2019-08-14 10:22 UTC, merged